STSEG SEGMENT PARA STACK 'STACK' ; STDEG - segment name, SEGMENT - reserved word
; PARA - alignment type(paragraph), STACK - for any future segment linking, 'STACK' - name for linking
DB 64 DUP ( 'STACK' )
STSEG ENDS

DSEG SEGMENT PARA PUBLIC 'DATA'
SOURCE DB 10, 20, 30, 40
DEST DB 4 DUP ( '?' )
DSEG ENDS

CSEG SEGMENT PARA PUBLIC 'CODE'
MAIN PROC FAR
ASSUME CS: CSEG, DS: DSEG, SS: STSEG   ; WHICH SEGMENT IS ATTACHED TO WHICH REGISTER
; return address
PUSH DS
MOV AX, 0 
; or XOR AX, AX
PUSH AX
; initializing DS
MOV AX, DSEG
MOV DS, AX
; clear the array
MOV DEST, 0
MOV DEST+1, 0
MOV DEST+2, 0
MOV DEST+3, 0
; forwarding
MOV AL, SOURCE
MOV DEST+3, AL
MOV AL, SOURCE+1
MOV DEST+2, AL
MOV AL, SOURCE+2
MOV DEST+1, AL
MOV AL, SOURCE+3
MOV DEST, AL

RET
MAIN ENDP   ;END OF PROCEDURE
CSEG ENDS   ;END OF CODE SEGMENT
END MAIN    ;END OF PROGRAM